#!/usr/bin/env python3
r"""Independent backend-facing hybrid CV-DV execution path.

This module is the circuit-side counterpart of ``clean_core.py``. It translates
the dense target mathematics into bosonic-qiskit operations while keeping all
backend-specific sign and layout conventions localized in one place.

The target joint evolution implemented here is the first-order Trotterization
of

    H_joint = x_hat ⊗ L + I ⊗ H,

with

    x_hat = (a + a^\dagger) / sqrt(2).

The exact DV reference against which the result is compared remains

    U_ref(T) = exp(-(L + i H) T).
"""

from __future__ import annotations

from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

import numpy as np

from clean_core import (
    CleanRunResult,
    EvolutionSpec,
    KernelSpec,
    PauliSystemSpec,
    PauliTerm,
    StatePrepSpec,
    coefficient_backend_gap,
    exact_reference_map,
    exact_truncated_cv_map,
    fit_global_scale,
    generator_matrix,
    normalize_vector,
    reorder_physics_to_qiskit,
    state_fidelity,
    system_blocks,
)
from clean_oracles import (
    OraclePreparation,
    compute_lchs_coefficients,
    detect_statevector_layout,
    fidelity_density_matrix_vs_pure,
    postselect_cv_output,
    prepare_cv_oracle,
)


def _require_backend() -> Tuple[Any, Any, Any, Any, Any]:
    """Import runtime-only backend dependencies on demand."""

    try:
        from bosonic_qiskit import CVCircuit, QumodeRegister
        from bosonic_qiskit import util as cv_util
        from qiskit import QuantumRegister
    except ImportError as exc:
        raise ImportError(
            "clean_hybrid requires bosonic_qiskit and qiskit for runtime execution."
        ) from exc

    try:
        from bosonic_qiskit.kraus import PhotonLossNoisePass
    except ImportError:
        PhotonLossNoisePass = None

    return CVCircuit, QumodeRegister, QuantumRegister, cv_util, PhotonLossNoisePass


def _is_power_of_two(value: int) -> bool:
    """Return whether ``value`` is a positive power of two."""

    return value > 0 and (value & (value - 1)) == 0


def _real_coeff(coeff: complex, *, tol: float = 1e-10) -> float:
    """Validate that a Pauli coefficient is real within tolerance."""

    if abs(np.imag(coeff)) > tol:
        raise ValueError(f"Expected a real Pauli coefficient, got {coeff}.")
    return float(np.real(coeff))


def _bosonic_sq_for_prepare(r: float) -> float:
    """Convert the clean squeezing sign to bosonic-qiskit's convention."""

    # bosonic_qiskit uses the opposite sign relative to the dense hbar=1 convention.
    return -float(r)


def _bosonic_sq_for_postselect(r: float) -> float:
    """Return the postselection squeezing used at circuit end."""

    # Applying S^\dagger(r) before the Fock-|0> slice implements <0|S^\dagger(r).
    return float(r)


def _conditional_displacement_alpha(lam: float) -> complex:
    """Map the hybrid coupling strength to a displacement amplitude.

    Under ``hbar = 1`` the hybrid factor generated by ``x_hat`` is

        exp(-i lambda x_hat) = D(-i lambda / sqrt(2)).
    """

    # exp(-i lam x_hat), x_hat=(a+a^\dagger)/sqrt(2), equals D(-i lam / sqrt(2)).
    return -1.0j * float(lam) / np.sqrt(2.0)


def _apply_oracle_to_circuit(
    qc: Any,
    mode: Any,
    oracle: OraclePreparation,
    *,
    law_eberly_qubit: Optional[Any] = None,
) -> None:
    """Load the prepared CV oracle into the circuit.

    ``direct_injection`` is used for exact simulator-side preparation.
    ``snap_d_layers`` replays the optimized alternating SNAP+D sequence.
    ``law_eberly_pulses`` applies a compiled qubit-assisted Law-Eberly sequence.
    """

    if oracle.apply_mode == "direct_injection":
        qc.cv_initialize(np.asarray(oracle.prepared_state, dtype=complex), mode)
        return

    if oracle.apply_mode == "snap_d_layers":
        for thetas, alpha in zip(oracle.snap_thetas_per_layer, oracle.snap_alphas_per_layer):
            for level, theta in enumerate(thetas):
                if abs(float(theta)) > 1e-12:
                    qc.cv_snap(float(theta), level, mode)
            qc.cv_d(alpha, mode)
        return

    if oracle.apply_mode == "law_eberly_pulses":
        if law_eberly_qubit is None:
            raise ValueError("law_eberly_pulses requires a Law-Eberly auxiliary qubit.")
        # Bosonic Qiskit's JC convention uses |e> = |0> and |g> = |1>.
        qc.x(law_eberly_qubit)
        for pulse in oracle.law_eberly_pulses:
            if abs(float(pulse.theta)) <= 1e-12:
                continue
            if pulse.kind == "jc":
                qc.cv_jc(float(pulse.theta), float(pulse.phi), mode, law_eberly_qubit)
            elif pulse.kind == "r":
                qc.r(float(pulse.theta), float(pulse.phi), law_eberly_qubit)
            elif pulse.kind == "sqr":
                qc.cv_sqr(
                    float(pulse.theta),
                    float(pulse.phi),
                    int(pulse.level),
                    mode,
                    law_eberly_qubit,
                )
            else:
                raise ValueError(f"Unknown Law-Eberly pulse kind '{pulse.kind}'.")
        return

    raise ValueError(f"Unknown oracle apply_mode '{oracle.apply_mode}'.")


def _initialize_dv_state(qc: Any, qreg: Any, init_state: np.ndarray) -> None:
    """Initialize the DV register from a physics-ordered statevector."""

    physics_state = normalize_vector(init_state)
    qiskit_state = reorder_physics_to_qiskit(physics_state, len(qreg))
    support = np.where(np.abs(qiskit_state) > 1e-12)[0]
    if support.size == 1 and abs(abs(qiskit_state[int(support[0])]) - 1.0) <= 1e-12:
        basis_index = int(support[0])
        for idx, qubit in enumerate(qreg):
            if (basis_index >> idx) & 1:
                qc.x(qubit)
        return
    qc.initialize(qiskit_state, list(qreg))


def _apply_basis_change_forward(qc: Any, qreg: Any, pauli_label: str) -> None:
    """Rotate each active qubit into the Z basis for Pauli compilation."""

    for idx, ch in enumerate(pauli_label):
        if ch == "X":
            qc.h(qreg[idx])
        elif ch == "Y":
            qc.rz(np.pi / 2.0, qreg[idx])
            qc.h(qreg[idx])


def _apply_basis_change_inverse(qc: Any, qreg: Any, pauli_label: str) -> None:
    """Undo ``_apply_basis_change_forward``."""

    for idx in reversed(range(len(pauli_label))):
        ch = pauli_label[idx]
        if ch == "X":
            qc.h(qreg[idx])
        elif ch == "Y":
            qc.h(qreg[idx])
            qc.rz(-np.pi / 2.0, qreg[idx])


def _active_qubits(pauli_label: str) -> List[int]:
    """Return the non-identity qubit positions of a Pauli string."""

    return [idx for idx, ch in enumerate(pauli_label) if ch != "I"]


def _apply_hybrid_z_parity_block(qc: Any, mode: Any, qreg: Any, active: Sequence[int], alpha: complex) -> None:
    """Apply the controlled displacement for a Z-parity string.

    After basis changes, every Pauli string is reduced to a Z-parity operator.
    The multi-qubit parity is compressed onto one target qubit with a CNOT
    ladder, a controlled displacement is applied, and then the ladder is
    uncomputed.
    """

    if not active:
        qc.cv_d(alpha, mode)
        return

    if len(active) == 1:
        qc.cv_c_d(alpha, mode, qreg[active[0]])
        return

    target = active[-1]
    for control in active[:-1]:
        qc.cx(qreg[control], qreg[target])
    qc.cv_c_d(alpha, mode, qreg[target])
    for control in reversed(active[:-1]):
        qc.cx(qreg[control], qreg[target])


def _apply_hybrid_pauli_factor(qc: Any, mode: Any, qreg: Any, pauli_term: PauliTerm, dt: float) -> None:
    """Compile one ``L``-term Trotter factor into the hybrid circuit.

    For a real Pauli coefficient ``c`` this implements the factor generated by

        exp(-i dt c x_hat ⊗ P),

    by changing basis into a Z-parity frame, applying a conditional
    displacement, and undoing the basis change.
    """

    coeff = _real_coeff(pauli_term.coeff)
    if abs(coeff) < 1e-15:
        return

    lam = coeff * dt
    alpha = _conditional_displacement_alpha(lam)
    active = _active_qubits(pauli_term.label)
    _apply_basis_change_forward(qc, qreg, pauli_term.label)
    _apply_hybrid_z_parity_block(qc, mode, qreg, active, alpha)
    _apply_basis_change_inverse(qc, qreg, pauli_term.label)


def _apply_dv_pauli_rotation(qc: Any, qreg: Any, pauli_term: PauliTerm, dt: float) -> None:
    """Compile one ``H``-term Trotter factor into DV-only gates.

    For a real Pauli coefficient ``c`` this applies

        exp(-i dt c P)

    using the standard basis-change-plus-parity-ladder construction.
    """

    coeff = _real_coeff(pauli_term.coeff)
    if abs(coeff) < 1e-15:
        return

    theta = coeff * dt
    active = _active_qubits(pauli_term.label)
    if not active:
        return

    _apply_basis_change_forward(qc, qreg, pauli_term.label)
    if len(active) == 1:
        qc.rz(2.0 * theta, qreg[active[0]])
    else:
        target = active[-1]
        for control in active[:-1]:
            qc.cx(qreg[control], qreg[target])
        qc.rz(2.0 * theta, qreg[target])
        for control in reversed(active[:-1]):
            qc.cx(qreg[control], qreg[target])
    _apply_basis_change_inverse(qc, qreg, pauli_term.label)


def _apply_first_order_trotter(
    qc: Any,
    mode: Any,
    qreg: Any,
    *,
    l_terms: Sequence[PauliTerm],
    h_terms: Sequence[PauliTerm],
    total_time: float,
    n_trotter_steps: int,
) -> None:
    """Apply a first-order Trotter product over ``L`` and ``H`` terms."""

    dt = total_time / n_trotter_steps
    for _ in range(n_trotter_steps):
        for term in l_terms:
            _apply_hybrid_pauli_factor(qc, mode, qreg, term, dt)
        for term in h_terms:
            _apply_dv_pauli_rotation(qc, qreg, term, dt)


def circuit_resource_report(qc: Any) -> Dict[str, Any]:
    """Return basic circuit-size diagnostics."""

    return {
        "depth": int(qc.depth()),
        "size": int(qc.size()),
        "count_ops": {str(k): int(v) for k, v in dict(qc.count_ops()).items()},
    }


def build_hybrid_circuit(
    system: PauliSystemSpec,
    kernel: KernelSpec,
    prep: StatePrepSpec,
    evolution: EvolutionSpec,
    *,
    coeffs: Optional[np.ndarray] = None,
    oracle: Optional[OraclePreparation] = None,
) -> Tuple[Any, OraclePreparation, Dict[str, Any]]:
    """Build the full hybrid CV-DV circuit for one clean run.

    The circuit structure is:

    1. Prepare the CV oracle state.
    2. Apply the preparation squeeze ``S(r_prime)``.
    3. Initialize the DV register.
    4. Apply first-order Trotterized hybrid evolution.
    5. Apply the postselection squeeze used before the Fock-``|0>`` slice.

    Args:
        system: Pauli-decomposed DV problem specification.
        kernel: Kernel hyperparameters and truncation.
        prep: CV state-preparation method specification.
        evolution: Trotter and readout settings.
        coeffs: Optional precomputed coefficient vector.
        oracle: Optional precomputed oracle preparation.

    Returns:
        Tuple ``(qc, oracle, build_meta)`` containing the backend circuit, the
        resolved oracle preparation, and lightweight build metadata.

    Raises:
        ValueError: If ``kernel.n_fock`` is not a power of two.
    """

    if not _is_power_of_two(kernel.n_fock):
        raise ValueError("kernel.n_fock must be a power of two for bosonic_qiskit.")

    CVCircuit, QumodeRegister, QuantumRegister, _, _ = _require_backend()

    if coeffs is None:
        coeffs = compute_lchs_coefficients(kernel)
    if oracle is None:
        oracle = prepare_cv_oracle(kernel, prep, coeffs=coeffs)

    qmr = QumodeRegister(
        num_qumodes=1,
        num_qubits_per_qumode=int(np.log2(kernel.n_fock)),
    )
    le_reg = None
    le_qubit = None
    if oracle.apply_mode == "law_eberly_pulses":
        le_reg = QuantumRegister(1, "le")
    qbr = QuantumRegister(system.n_qubits, "q")
    qc = CVCircuit(le_reg, qbr, qmr) if le_reg is not None else CVCircuit(qbr, qmr)
    mode = qmr[0]
    if le_reg is not None:
        le_qubit = le_reg[0]

    _apply_oracle_to_circuit(qc, mode, oracle, law_eberly_qubit=le_qubit)

    if abs(kernel.r_prime) > 1e-14:
        qc.cv_sq(_bosonic_sq_for_prepare(kernel.r_prime), mode)

    _initialize_dv_state(qc, qbr, system.init_state)

    filtered_l_terms = [term for term in system.l_terms if abs(term.coeff) > 1e-15]
    filtered_h_terms = [term for term in system.h_terms if abs(term.coeff) > 1e-15]
    _apply_first_order_trotter(
        qc,
        mode,
        qbr,
        l_terms=filtered_l_terms,
        h_terms=filtered_h_terms,
        total_time=system.total_time,
        n_trotter_steps=evolution.n_trotter_steps,
    )

    if abs(kernel.r_target) > 1e-14:
        qc.cv_sq(_bosonic_sq_for_postselect(kernel.r_target), mode)

    build_meta = {
        "n_dv_qubits": int(system.n_qubits),
        "n_fock": int(kernel.n_fock),
        "coeff_backend": kernel.coeff_backend,
        "state_prep_method": prep.method,
        "n_trotter_steps": int(evolution.n_trotter_steps),
        "n_law_eberly_aux_qubits": int(le_reg is not None),
    }
    return qc, oracle, build_meta


def _simulate_with_readout(
    qc: Any,
    *,
    evolution: EvolutionSpec,
    kernel: KernelSpec,
    system: PauliSystemSpec,
    n_prefix_qubits: int = 0,
    prefix_qubit_values: Sequence[int] = (),
) -> Dict[str, Any]:
    """Run the backend simulation and apply the requested readout rule."""

    _, _, _, cv_util, PhotonLossNoisePass = _require_backend()
    layout = detect_statevector_layout(kernel.n_fock, system.n_qubits + n_prefix_qubits)

    if evolution.readout_mode == "postselect_density_matrix":
        qc.save_density_matrix()
        noise_pass = None
        if evolution.photon_loss_rate > 0.0:
            if PhotonLossNoisePass is None:
                raise ImportError("PhotonLossNoisePass is unavailable in this bosonic_qiskit build.")
            noise_pass = PhotonLossNoisePass(
                photon_loss_rates=evolution.photon_loss_rate,
                circuit=qc,
                time_unit="s",
            )

        _, result, _ = cv_util.simulate(
            qc,
            shots=1,
            return_fockcounts=False,
            add_save_statevector=False,
            noise_passes=noise_pass,
        )
        density_matrix = np.asarray(result.data(0)["density_matrix"], dtype=complex)
        readout = postselect_cv_output(
            density_matrix,
            readout_mode=evolution.readout_mode,
            layout=layout,
            max_fock_level=kernel.n_fock,
            n_dv_qubits=system.n_qubits,
            n_prefix_qubits=n_prefix_qubits,
            prefix_qubit_values=prefix_qubit_values,
        )
        readout["layout"] = layout
        readout["density_matrix"] = density_matrix
        return readout

    state, _, _ = cv_util.simulate(
        qc,
        shots=1,
        return_fockcounts=False,
        add_save_statevector=True,
    )
    statevector = np.asarray(state.data, dtype=complex)
    readout = postselect_cv_output(
        statevector,
        readout_mode=evolution.readout_mode,
        layout=layout,
        max_fock_level=kernel.n_fock,
        n_dv_qubits=system.n_qubits,
        n_prefix_qubits=n_prefix_qubits,
        prefix_qubit_values=prefix_qubit_values,
    )
    readout["layout"] = layout
    readout["statevector"] = statevector
    return readout


def run_clean_lchs(
    system: PauliSystemSpec,
    kernel: KernelSpec,
    prep: StatePrepSpec,
    evolution: EvolutionSpec,
    *,
    coeffs: Optional[np.ndarray] = None,
    oracle: Optional[OraclePreparation] = None,
) -> CleanRunResult:
    """Execute one end-to-end clean CV-DV LCHS run.

    This routine ties together coefficient generation, CV oracle preparation,
    hybrid circuit construction, backend simulation, and comparison against two
    references:

    1. the exact DV target ``exp(-(L + i H) T)``,
    2. the exact truncated CV reference induced by the prepared oscillator
       state.

    Args:
        system: Pauli-decomposed DV problem specification.
        kernel: Kernel hyperparameters and truncation.
        prep: CV state-preparation specification.
        evolution: Trotter and readout settings.
        coeffs: Optional precomputed coefficient vector reused across repeated
            runs at the same kernel point.
        oracle: Optional precomputed oracle preparation. This is used by the
            sweep client to avoid recomputing a warm-started SNAP+D solution
            before circuit construction.

    Returns:
        ``CleanRunResult`` containing fidelities, relative errors, raw vectors,
        and circuit resource counts.
    """

    if coeffs is None:
        coeffs = compute_lchs_coefficients(kernel)
    coeff_gap = coefficient_backend_gap(kernel)
    if oracle is None:
        oracle = prepare_cv_oracle(kernel, prep, coeffs=coeffs)

    qc, oracle, build_meta = build_hybrid_circuit(
        system,
        kernel,
        prep,
        evolution,
        coeffs=coeffs,
        oracle=oracle,
    )
    n_prefix_qubits = int(build_meta.get("n_law_eberly_aux_qubits", 0))
    prefix_values = (1,) if n_prefix_qubits else ()
    readout = _simulate_with_readout(
        qc,
        evolution=evolution,
        kernel=kernel,
        system=system,
        n_prefix_qubits=n_prefix_qubits,
        prefix_qubit_values=prefix_values,
    )

    ref_map = exact_reference_map(system)
    ref_vec = ref_map @ normalize_vector(system.init_state)

    truncated_oracle_map = exact_truncated_cv_map(system, kernel, seed_state=oracle.prepared_state)
    truncated_oracle_vec = truncated_oracle_map @ normalize_vector(system.init_state)

    truncated_ideal_map = exact_truncated_cv_map(system, kernel, seed_state=coeffs)
    truncated_ideal_vec = truncated_ideal_map @ normalize_vector(system.init_state)

    observed_vec = np.asarray(readout["observed_vector"], dtype=complex).reshape(-1)
    post_prob = float(readout["postselection_probability"])

    scale_exact, rel_exact = fit_global_scale(observed_vec, ref_vec)
    scale_trunc, rel_trunc = fit_global_scale(observed_vec, truncated_oracle_vec)

    if "postselected_density_matrix" in readout:
        rho_post = np.asarray(readout["postselected_density_matrix"], dtype=complex)
        fidelity_exact = fidelity_density_matrix_vs_pure(rho_post, ref_vec)
        fidelity_trunc = fidelity_density_matrix_vs_pure(rho_post, truncated_oracle_vec)
    else:
        fidelity_exact = state_fidelity(observed_vec, ref_vec)
        fidelity_trunc = state_fidelity(observed_vec, truncated_oracle_vec)

    resources = circuit_resource_report(qc)
    l_block, h_block = system_blocks(system)

    metadata: Dict[str, Any] = {
        **build_meta,
        "generator_matrix": generator_matrix(system),
        "l_block": l_block,
        "h_block": h_block,
        "oracle_metadata": dict(oracle.metadata),
        "oracle_apply_mode": oracle.apply_mode,
        "layout": readout["layout"],
        "ideal_truncated_vector": truncated_ideal_vec,
        "ideal_truncated_map": truncated_ideal_map,
        "ideal_vs_reference_fidelity": state_fidelity(truncated_ideal_vec, ref_vec),
        "oracle_vs_ideal_fidelity": state_fidelity(truncated_oracle_vec, truncated_ideal_vec),
        "statevector": readout.get("statevector"),
        "density_matrix": readout.get("density_matrix"),
        "postselected_density_matrix": readout.get("postselected_density_matrix"),
    }

    return CleanRunResult(
        system_label=system.label,
        coeff_backend=kernel.coeff_backend,
        state_prep_method=prep.method,
        readout_mode=evolution.readout_mode,
        postselection_probability=post_prob,
        fidelity_vs_exact=float(fidelity_exact),
        fidelity_vs_truncated=float(fidelity_trunc),
        rel_error_vs_exact=float(rel_exact),
        rel_error_vs_truncated=float(rel_trunc),
        scale_vs_exact=complex(scale_exact),
        scale_vs_truncated=complex(scale_trunc),
        coeff_backend_gap=float(coeff_gap),
        oracle_fidelity=float(oracle.oracle_fidelity),
        observed_vector=observed_vec,
        exact_reference_vector=ref_vec,
        exact_truncated_vector=truncated_oracle_vec,
        exact_reference_map=ref_map,
        exact_truncated_map=truncated_oracle_map,
        circuit_depth=int(resources["depth"]),
        circuit_size=int(resources["size"]),
        count_ops=resources["count_ops"],
        metadata=metadata,
    )
